Update PlayerMovement.cs
half controls works but joystick is giving errors

UnassignedReferenceException: The variable player of PlayerMovement has not been assigned.
You probably need to assign the player variable of the PlayerMovement script in the inspector.
UnityEngine.Transform.get_position () <0x150a95bfe80 + 0x0006a> in <a278ebd44ab0472bb8e638263e06cd61>:0
UnityEngine.Transform.Translate (UnityEngine.Vector3 translation, UnityEngine.Space relativeTo) (at C:/buildslave/unity/build/Runtime/Transform/ScriptBindings/Transform.bindings.cs:118)
UnityEngine.Transform.Translate (UnityEngine.Vector3 translation) (at C:/buildslave/unity/build/Runtime/Transform/ScriptBindings/Transform.bindings.cs:123)
PlayerMovement.FixedUpdate () (at Assets/Scripts/PlayerMovement.cs:80)